package Project.Enums;

public enum Incumbents {

    BUDDY_CARTER_R,
    SANFORD_BISHOP_D,
    DREW_FERGUSON_R,
    HANK_JOHNSON_D,
    NIKEMA_WILLIAMS_D,
    LUCY_MCBATH_D,
    CAROLYN_BORDEAUX_D,
    AUSTIN_SCOTT_R,
    ANDREW_CLYDE_R,
    JODY_HICE_R,
    BARRY_LOUDERMILK_R,
    RICK_ALLEN_R,
    DAVID_SCOTT_D,
    MARJORIE_TAYLOR_GREENE_R

}
